kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# networking:
  # the default CNI will not be installed
  # disableDefaultCNI: true
nodes:
- role: control-plane
- role: worker
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "service-account-issuer": "kubernetes.default.svc"
        "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"

